(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/kuori/Documentos/web2py/applications/Correlativas/controllers/horario.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# intente algo como\ndef index():\n    grid = SQLFORM.smartgrid(db.horario_clases)\n    return dict(message="hello from horario.py", grid = grid)\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/kuori/Documentos/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/kuori/Documentos/web2py/applications/Correlativas/controllers/horario.py", line 7, in <module>\n  File "/home/kuori/Documentos/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/kuori/Documentos/web2py/applications/Correlativas/controllers/horario.py", line 4, in index\n    grid = SQLFORM.smartgrid(db.horario_clases)\n  File "/home/kuori/Documentos/web2py/gluon/packages/dal/pydal/base.py", line 906, in __getattr__\n    return super(DAL, self).__getattr__(key)\n  File "/home/kuori/Documentos/web2py/gluon/packages/dal/pydal/helpers/classes.py", line 348, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.